version: "3.8"

services:
  web:
    image: ghcr.io/vuorinet/ben:latest
    container_name: ben-web
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./ben.db:/app/data/ben.db
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - DATABASE_DIR=/app/data
      - PORT=5000
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
